apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    app: nodeapp
    component: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
      component: app
  template:
    metadata:
      name: app-pod
      labels:
        app: nodeapp
        component: app
    spec:
      containers:
      - image: anisk/nodeapp:1.1
        name: nodeapp
        env:
        - name: DATABASE_HOST
          value: mongo
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace