---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: nodeapp
    component: mongo
spec:
  ports:
  - name: dbport
    port: 27017
    protocol: TCP
    targetPort: 27017
  - name: monitorport
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: nodeapp
    component: mongo
    
