---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: nodeapp
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
      component: mongo
  template:
    metadata:
      name: mongo
      labels:
        app: nodeapp
        component: mongo
        # As seen in node-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9001"
    spec:
      spec:
      containers:
      - image: mongo:3.2
        name: mongo
        volumeMounts:
        - name: db-pv
          mountPath: /data/db
      - image: anisk/mongo-exporter:1.0
        name: mongo-exporter
        # For Prometheus discovery *Not Working WO this config!*
        ports:
        - containerPort: 9001
          name: metrics
        env:
        - name: MONGODB_URL 
          value: 'mongodb://localhost:27017'
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: db-pv
        persistentVolumeClaim:
          claimName: mongo-pvc