version: ‘3.3’
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - nodeapp
  nodeapp:
    build: ./app
    image: ${USERNAME}/nodeapp:1.0
    ports:
      - 8081:8081/tcp
    networks:
      - nodeapp
volumes:
  post_db:
networks:
  nodeapp: