version: ‘3’
services:
  post_db:
    image: mongo:${MONGOVER}
    volumes:
      - post_db:/data/db
    networks:
      - nodeapp
  nodeapp:
    build: ./app
    image: ${USERNAME}/nodeapp:${IMAGETAG}
    ports:
      - ${APPPORT}:${APPPORT}/tcp
    networks:
      - nodeapp
volumes:
  post_db:
networks:
  nodeapp: